version: 2
updates:
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore"
      include: "scope"

  # Go modules
  - package-ecosystem: gomod
    directory: /protocube
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
      include: "scope"
  
  - package-ecosystem: gomod
    directory: /slimepacks
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
      include: "scope"
  
  - package-ecosystem: gomod
    directory: /daemon
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
      include: "scope"

  # Maven projects
  - package-ecosystem: maven
    directory: /S4J
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
      include: "scope"
  
  - package-ecosystem: maven
    directory: /vsls
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
      include: "scope"
  
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
      include: "scope"