
# Enable debug logging
debug: false

# Logical location name
location: us-east-1

# Display name of this daemon
name: SLS

api:
  url: https://daemon.sls.net:5585 # The url used to contact this api
  host: 0.0.0.0
  port: 5585
  tls:
    enabled: true
    cert: /etc/ssl/certs/sls.crt
    key: /etc/ssl/private/sls.key

remote:
  url: https://protocube.sls.net:5620
  token: SLS_YOUR_NODEAPIKEY

system:
  root_directory: /var/lib/sls
  log_directory: /var/log/sls
  allowed_mounts: []
  allowed_origins: []
  timezone: UTC
  disk_check_interval: 150
  openat_mode: "auto"

  data: /var/lib/sls/data
  volumes: /var/lib/sls/volumes
  servers: /var/lib/sls/servers

  user:
    uid: 988
    gid: 988
    rootless:
      enabled: false
      container_uid: 0
      container_gid: 0

allocations:
  - address: 0.0.0.0
    alias: host.docker.internal
    force_outgoing_ip: false
    ports: 30000-31000

docker:
  network:
    interface: 172.28.0.1
    dns:
      - 1.1.1.1
      - 1.0.0.1
    name: sls_nw
    ispn: false
    driver: bridge
    network_mode: sls_nw
    is_internal: false
    enable_icc: true
    network_mtu: 1500
    interfaces:
      v4:
        subnet: 172.28.0.0/16
        gateway: 172.28.0.1
      v6:
        subnet: fdba:17c8:6c94::/64
        gateway: fdba:17c8:6c94::1011
  domainname: ""
  registries: {}
  tmpfs_size: 100
  container_pid_limit: 512
  installer_limits:
    memory: 1024
    cpu: 100
  overhead:
    override: false
    default_multiplier: 1.05
    multipliers: {}
  use_performant_inspect: true
  userns_mode: ""
  log_config:
    type: local
    config:
      compress: "false"
      max-file: "1"
      max-size: 5m
      mode: non-blocking

throttles:
  enabled: true
  lines: 2000
  line_reset_interval: 100
remote_query:
  timeout: 30
  boot_servers_per_page: 50
allow_cors_private_network: false
