package client

import (
	"context"

	"protoxon.com/sls/protocube/models"
)

type NodeClient interface {
	SetToken(token string)
	GetToken() string
	Server(id string) ServerClient

	// Request types
	Get(ctx context.Context, path string, query q) (*Response, error)
	Post(ctx context.Context, path string, data interface{}) (*Response, error)
	Delete(ctx context.Context, path string) (*Response, error)

	// Requests
	CreateServer(context context.Context, request models.NodeCreateServerRequest) (models.CreateServerResponse, error)
	GetSystemInformation(context context.Context) (models.Information, error)
}

type nodeClient struct {
	client  *Client
	nodeId  string
	baseUrl string

	// The token is generated by protocube and is given
	// to the node for verification
	token string
}

// Server returns a server specific client bound to this node client.
func (nc *nodeClient) Server(id string) ServerClient {
	return NewServerClient(id, nc.nodeId).SetNodeClient(nc)
}

// SetToken sets the authentication token to use when making requests to the node
func (nc *nodeClient) SetToken(token string) {
	nc.token = token
}

// GetToken returns the authentication used for authenticating requests to the node
func (nc *nodeClient) GetToken() string {
	return nc.token
}

// CreateServer sends a request to create a new server on the remote node
// and returns the server's data upon successful creation.
func (nc *nodeClient) CreateServer(ctx context.Context, create models.NodeCreateServerRequest) (models.CreateServerResponse, error) {
	return Post[models.CreateServerResponse](nc, ctx, "/servers", create)
}

// GetSystemInformation fetches system information from the nodes system package
func (nc *nodeClient) GetSystemInformation(ctx context.Context) (models.Information, error) {
	return Get[models.Information](nc, ctx, "/system", nil)
}
