package client

import (
	"context"

	"protoxon.com/sls/protocube/models"
)

type NodeClient interface {
	SetToken(token string)
	GetToken() string
	Server(id string) ServerClient

	CreateServer(context context.Context, request models.NodeCreateServerRequest) (models.CreateServerResponse, error)
	GetServers(context context.Context, perPage int) ([]models.ServerData, error)
}

type nodeClient struct {
	client  *Client
	baseUrl string

	// The token is generated by protocube and is given
	// to the node for verification
	token string
}

// Server returns a server-specific client bound to this node client.
func (nc *nodeClient) Server(id string) ServerClient {
	return &serverClient{
		node: nc,
		id:   id,
	}
}

func (nc *nodeClient) SetToken(token string) {
	nc.token = token
}

func (nc *nodeClient) GetToken() string {
	return nc.token
}

// CreateServer sends a request to create a new server on the remote node
// and returns the server's data upon successful creation.
func (nc *nodeClient) CreateServer(ctx context.Context, create models.NodeCreateServerRequest) (models.CreateServerResponse, error) {
	return Post[models.CreateServerResponse](nc, ctx, "/servers", create)
}

func (nc *nodeClient) GetServers(ctx context.Context, perPage int) ([]models.ServerData, error) {
	//TODO implement me
	panic("implement me")
}
